### ISSUE TITLE
Higher character count?

### ISSUE THREAD

**Issue by metruzanca** [benawad/vsinder#122] opened 2020-12-15 08:35 UTC
I can't be the only one disapointed to see only 600 chars allows. What if I want to fill the entire screen? (ascii art wink wonk)

Also can we get the full unicode so that we can use braile characters?

If it doesn't already, ability to enable font ligatures? (I know some people hate them, and if they do its a red flag for me.)

**Comment by unDeadHerbs** [comment] 2020-12-23 14:00
Duplicate of #125, #94 and #16.

**Closed by unDeadHerbs** 2020-12-23 14:00 UTC
Labels: lp
