### ISSUE TITLE
utf8mb4 chars dont work

### ISSUE THREAD

**Issue by jonnytest1** [benawad/vsinder#43] opened 2020-12-10 17:51 UTC
database doesnt support emojis  (probably need to switch to utf8mb4 collation)

**Comment by unDeadHerbs** [comment] 2020-12-23 13:24
Where and what does this cause as a problem?

**Comment by jonnytest1** [comment] 2020-12-28 06:07
i cant post emojis in text fields

**Comment by unDeadHerbs** [comment] 2020-12-28 12:41
Emoji work in the chat on Android.  Are you on iPhone or VScode?

**Comment by jonnytest1** [comment] 2020-12-29 05:09
they dont work in code previews

**Comment by unDeadHerbs** [comment] 2020-12-29 06:03
Duplicate of #16.

**Closed** 2020-12-29 06:03 UTC
Labels: lp, question
