### ISSUE TITLE
Location service

### ISSUE THREAD

**Issue by AlexNodex** [benawad/vsinder#142] opened 2020-12-17 08:22 UTC
I noticed on your recent Youtube video about getting DDOS'd that you're looking for a new provider to deal with locations as Google are charging you lots of money for this.

You should check out https://community.algolia.com/places/ 

They have a free tier and can be used directly from the client or via a backend request.

As a company we've used Algolia for many years and we utilise their places API in most of our products and they're amazing. The results are fast, typo tolerant and relevant.

**Comment by PoOwAa** [comment] 2020-12-18 12:10
Individual users have a different IP address, so the extension can use the free tier without registration.

Or if you want to register and use an API key, then the extension should call the backend API which can hide the actual API key. It can work like a proxy.

**Comment by rugk** [comment] 2021-01-24 19:00
Yeah, generally I'd suggest to look for some service based on OpenStreetMap (OSM) or so: https://switch2osm.org/other-uses/
The thing to look for seem to be _Geocoding services_.

**Comment by unDeadHerbs** [comment] 2021-01-24 19:06
Duplicate of #135.

**Closed** 2021-01-24 19:06 UTC
