### ISSUE TITLE
[Feature Request]  reading marks under messages 

### ISSUE THREAD

**Issue by Adamkaram** [benawad/vsinder#171] opened 2020-12-22 07:33 UTC

**Comment by unDeadHerbs** [comment] 2020-12-22 07:52
Duplicate of #156.

**Comment by unDeadHerbs** [comment] 2020-12-22 07:56
On that note, @benawad, can I have permission to close/tag issues?

**Comment by benawad** [comment] 2020-12-23 04:00
@unDeadHerbs invited you as a collaborator

**Closed by benawad** 2020-12-23 04:00 UTC
