### ISSUE TITLE
Pasting gifs in the chat on mobile

### ISSUE THREAD

**Issue by MiltonChung** [benawad/vsinder#105] opened 2020-12-14 06:03 UTC
I'm using Google keyboard on iPhone and I can copy gifs right from the keyboard but cannot paste gifs into the chat. Normal copy and paste texts works fine but supporting gifs would be great!

**Comment by unDeadHerbs** [comment] 2020-12-14 09:24
Duplicate of #92.

**Closed** 2020-12-23 13:33 UTC
Labels: lp
