### ISSUE TITLE
Long press left and right arrow keys

### ISSUE THREAD

**Issue by dorianbucknor** [benawad/vsinder#206] opened 2021-02-02 01:36 UTC
Left and right arrow keys when long pressed swipes a lot of profiles. Recommend that a user can only swipe once per key pressed down. Found this by accident as it is not normal for someone to just long press down given the situation.

**Comment by unDeadHerbs** [comment] 2021-02-02 11:47
Duplicate of #193.

**Closed** 2021-02-02 11:48 UTC
