### ISSUE TITLE
[Feature request] Add possibility to see liked matches profiles after giving like

### ISSUE THREAD

**Issue by JJJGGGG** [benawad/vsinder#75] opened 2020-12-12 00:44 UTC
Hi. I love the app. But maybe it would be interesting to have this feature, like in profile->liked profiles. I'll try to make a pr but I'm not so good with react-native lol.

**Comment by siramk** [comment] 2020-12-12 05:40
It would also be nice to see the profiles who liked us

**Comment by unDeadHerbs** [comment] 2020-12-23 13:18
Depending on how #20 progresses, this could become a privacy concern. (It also could even without it.)  Closing as duplicate of #78.

**Closed by unDeadHerbs** 2020-12-23 13:18 UTC
Labels: lp
